name: Deploy

on:
  workflow_run:
    workflows: ["CI build"]
    types:
      - completed
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: dkeysil/nostrin_bot:latest
  run_latest_image:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Create config.yaml file
        run: |
          touch config.yaml
          echo "${{ secrets.CONFIG_YAML }}" > config.yaml

      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          CONFIG_YAML: ${{ secrets.CONFIG_YAML }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_SECRET }}
          envs: CONFIG_YAML
          script: |
            mkdir nostrin_bot
            rm nostrin_bot/config.yaml
            echo $CONFIG_YAML > nostrin_bot/config.yaml

            docker pull dkeysil/nostrin_bot:latest
            docker stop nostrin_bot
            docker rm nostrin_bot
            docker run -d --restart=always --name nostrin_bot -v /home/$SSH_USERNAME/nostrin_bot/config.yaml:/project/config.yaml dkeysil/nostrin_bot:latest
